-- =====================================================================
-- BANK TRADING PLATFORM — SEED DATA
-- =====================================================================
-- Run AFTER schema.sql.
-- Passwords are intentionally omitted here (empty string placeholder).
-- Before going to production, replace every password_hash with a real
-- Argon2id encoded string generated by the Java application.
--
-- Insertion order matters because of FK constraints:
--   roles → permissions → role_permissions
--   → users (admin) → traders → clients → wallets
-- The trigger trg_users_enforce_creator blocks admin-role inserts unless
-- the creator is already an ADMIN, so we temporarily bypass it for the
-- seed admin, then re-enable checks for all subsequent rows.
-- =====================================================================

USE trading_platform;


-- =====================================================================
-- ROLES
-- =====================================================================

INSERT INTO roles (role_name) VALUES
    ('ADMIN'),    -- role_id = 1
    ('TRADER'),   -- role_id = 2
    ('CLIENT');   -- role_id = 3


-- =====================================================================
-- PERMISSIONS
-- =====================================================================

INSERT INTO permissions (permission_name, description) VALUES
    ('MANAGE_USERS',       'Create, update, and suspend trader and client accounts'),
    ('MANAGE_INSTRUMENTS', 'Add, edit, and delist tradable instruments'),
    ('MANAGE_RULES',       'Configure trading limits and risk parameters'),
    ('VIEW_ALL_TRADES',    'View every trade executed on the platform'),
    ('PLACE_ORDER',        'Submit buy/sell orders on behalf of a client'),
    ('CANCEL_ORDER',       'Cancel a pending or partially-filled order'),
    ('VIEW_OWN_PORTFOLIO', 'View own holdings, wallet balance, and trade history');


-- =====================================================================
-- ROLE → PERMISSION MAPPING
-- =====================================================================

-- ADMIN: platform management (no trading permissions by design)
INSERT INTO role_permissions (role_id, permission_id)
SELECT 1, permission_id
FROM   permissions
WHERE  permission_name IN (
    'MANAGE_USERS',
    'MANAGE_INSTRUMENTS',
    'MANAGE_RULES',
    'VIEW_ALL_TRADES'
);

-- TRADER: order execution only
INSERT INTO role_permissions (role_id, permission_id)
SELECT 2, permission_id
FROM   permissions
WHERE  permission_name IN (
    'PLACE_ORDER',
    'CANCEL_ORDER'
);

-- CLIENT: read-only self-service view
INSERT INTO role_permissions (role_id, permission_id)
SELECT 3, permission_id
FROM   permissions
WHERE  permission_name = 'VIEW_OWN_PORTFOLIO';


-- =====================================================================
-- SYSTEM ADMIN (seed — the only row allowed to have created_by = NULL)
-- =====================================================================
-- The trigger trg_users_enforce_creator permits NULL created_by only
-- when the users table is completely empty, which it is at this point.

INSERT INTO users (username, email, password_hash, password_algo, role_id, status, created_by)
VALUES (
    'sysadmin',
    'sysadmin@bank.local',
    -- TODO: replace with a real Argon2id hash from the Java app before production
    '$argon2id$v=19$m=65536,t=3,p=4$REPLACE_SALT$REPLACE_HASH',
    'argon2id',
    1,           -- ADMIN
    'ACTIVE',
    NULL         -- no creator; this is the bootstrap account
);

-- Capture the admin's user_id for use in subsequent inserts.
SET @admin_id = LAST_INSERT_ID();


-- =====================================================================
-- TRADERS  (5 accounts, created by the system admin)
-- =====================================================================

INSERT INTO users (username, email, password_hash, password_algo, role_id, status, created_by)
VALUES
    ('trader_arjun',   'arjun.mehta@bank.local',    '', 'argon2id', 2, 'ACTIVE', @admin_id),
    ('trader_priya',   'priya.sharma@bank.local',   '', 'argon2id', 2, 'ACTIVE', @admin_id),
    ('trader_rohan',   'rohan.verma@bank.local',    '', 'argon2id', 2, 'ACTIVE', @admin_id),
    ('trader_anika',   'anika.gupta@bank.local',    '', 'argon2id', 2, 'ACTIVE', @admin_id),
    ('trader_vikram',  'vikram.nair@bank.local',    '', 'argon2id', 2, 'ACTIVE', @admin_id);

-- Capture each trader's user_id in order of insertion.
SET @t1 = @admin_id + 1;
SET @t2 = @admin_id + 2;
SET @t3 = @admin_id + 3;
SET @t4 = @admin_id + 4;
SET @t5 = @admin_id + 5;

-- Trader-specific attributes
INSERT INTO traders (user_id, employee_code, department)
VALUES
    (@t1, 'EMP-001', 'Equities'),
    (@t2, 'EMP-002', 'Derivatives'),
    (@t3, 'EMP-003', 'Fixed Income'),
    (@t4, 'EMP-004', 'FX & Commodities'),
    (@t5, 'EMP-005', 'Equities');


-- =====================================================================
-- CLIENTS  (5 accounts, created by the system admin)
-- =====================================================================

INSERT INTO users (username, email, password_hash, password_algo, role_id, status, created_by)
VALUES
    ('client_sanjay',  'sanjay.kapoor@mail.com',    '', 'argon2id', 3, 'ACTIVE', @admin_id),
    ('client_neha',    'neha.joshi@mail.com',        '', 'argon2id', 3, 'ACTIVE', @admin_id),
    ('client_rahul',   'rahul.bansal@mail.com',      '', 'argon2id', 3, 'ACTIVE', @admin_id),
    ('client_divya',   'divya.iyer@mail.com',        '', 'argon2id', 3, 'ACTIVE', @admin_id),
    ('client_karan',   'karan.malhotra@mail.com',    '', 'argon2id', 3, 'ACTIVE', @admin_id);

SET @c1 = @admin_id + 6;
SET @c2 = @admin_id + 7;
SET @c3 = @admin_id + 8;
SET @c4 = @admin_id + 9;
SET @c5 = @admin_id + 10;

-- Client-specific attributes (KYC status & risk profile)
INSERT INTO clients (user_id, kyc_status, risk_profile)
VALUES
    (@c1, 'VERIFIED', 'HIGH'),
    (@c2, 'VERIFIED', 'MEDIUM'),
    (@c3, 'PENDING',  'LOW'),
    (@c4, 'VERIFIED', 'MEDIUM'),
    (@c5, 'REJECTED', 'HIGH');

-- Each client starts with an empty INR wallet.
-- Deposit funds through the application's deposit flow after onboarding.
INSERT INTO wallets (client_id, cash_balance, currency)
VALUES
    (@c1, 0.00, 'INR'),
    (@c2, 0.00, 'INR'),
    (@c3, 0.00, 'INR'),
    (@c4, 0.00, 'INR'),
    (@c5, 0.00, 'INR');


-- =====================================================================
-- TRADER ↔ CLIENT ASSIGNMENTS  (admin assigns each trader to one client)
-- =====================================================================
-- In production, assign based on relationship-manager pairings.
-- Here each trader covers one client as a starting baseline.

INSERT INTO trader_client_assignments (trader_id, client_id, assigned_by)
VALUES
    (@t1, @c1, @admin_id),   -- Arjun  manages Sanjay
    (@t2, @c2, @admin_id),   -- Priya  manages Neha
    (@t3, @c3, @admin_id),   -- Rohan  manages Rahul
    (@t4, @c4, @admin_id),   -- Anika  manages Divya
    (@t5, @c5, @admin_id);   -- Vikram manages Karan
